services:
  # ✅ Service Streamlit (ton app principale)
  - type: web
    name: ecocan-streamlit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: API_FOREST_URL
        value: https://api-forest-ecoscan.onrender.com
      - key: API_LINEAR_URL
        value: https://api-linear-ecoscan.onrender.com

  # ✅ API Random Forest
  - type: web
    name: api-forest-ecoscan
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python API_Random_Forest.py
    port: 5001

  # ✅ API Linear Regression
  - type: web
    name: api-linear-ecoscan
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python API_Lineaire_Reg.py
    port: 5000